apiVersion: v1
kind: Secret
metadata:
  name: backend-app-secret
  namespace: default
  labels:
    app: finance-tracker-backend
type: Opaque
stringData:
  DATABASE_URL: "jdbc:postgresql://postgres:5432/finance_tracker?serverTimezone=UTC"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "postgres"
  JWT_SECRET: "finance-tracker-jwt-secret-key-prod-2026-change-me"
  JWT_EXPIRATION: "86400000"
  LLAMAPARSE_API_KEY: "llx-CKiPLUKSHKERyEKY7zDRu83pThB03ksvVCbI5eoOCIF54ORA"
  DEEPSEEK_API_KEY: "sk-4818af27d9ee4b929f6e7ee98f9bfa87"
